name: adjoe
description: The official Flutter wrapper of the Playtime SDK.
version: 4.2.0
homepage: https://adjoe.io
documentation: https://docs.adjoe.io

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^16.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.adjoe.flutter.sdk
        pluginClass: SdkPlugin
      ios:
        pluginClass: SdkPlugin

publish_to: none
