// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// This interface is used to pass additional identifiers of the user.
class PlaytimeExtensions {
  PlaytimeExtensions({
    this.subId1,
    this.subId2,
    this.subId3,
    this.subId4,
    this.subId5,
  });

  /// An optional identifier that is provided back in the S2S payout URL.
  String? subId1;

  /// An optional identifier that is provided back in the S2S payout URL.
  String? subId2;

  /// An optional identifier that is provided back in the S2S payout URL.
  String? subId3;

  /// An optional identifier that is provided back in the S2S payout URL.
  String? subId4;

  /// An optional identifier that is provided back in the S2S payout URL.
  String? subId5;

  Object encode() {
    return <Object?>[
      subId1,
      subId2,
      subId3,
      subId4,
      subId5,
    ];
  }

  static PlaytimeExtensions decode(Object result) {
    result as List<Object?>;
    return PlaytimeExtensions(
      subId1: result[0] as String?,
      subId2: result[1] as String?,
      subId3: result[2] as String?,
      subId4: result[3] as String?,
      subId5: result[4] as String?,
    );
  }
}

/// The options passed to Playtime methods.
class PlaytimeOptions {
  PlaytimeOptions({
    this.userId,
    this.sdkHash,
    this.tokens,
    this.userProfile,
    this.params,
    this.extensions,
  });

  /// A custom identifier you must assign to each user.
  String? userId;

  /// The SDK hash for initialization.
  String? sdkHash;

  /// A list of tokens.
  List<String?>? tokens;

  /// User profile for targeting.
  PlaytimeUserProfile? userProfile;

  /// User acquisition parameters.
  PlaytimeParams? params;

  /// Extension IDs visible in S2S payouts.
  PlaytimeExtensions? extensions;

  Object encode() {
    return <Object?>[
      userId,
      sdkHash,
      tokens,
      userProfile?.encode(),
      params?.encode(),
      extensions?.encode(),
    ];
  }

  static PlaytimeOptions decode(Object result) {
    result as List<Object?>;
    return PlaytimeOptions(
      userId: result[0] as String?,
      sdkHash: result[1] as String?,
      tokens: (result[2] as List<Object?>?)?.cast<String?>(),
      userProfile: result[3] != null
          ? PlaytimeUserProfile.decode(result[3]! as List<Object?>)
          : null,
      params: result[4] != null
          ? PlaytimeParams.decode(result[4]! as List<Object?>)
          : null,
      extensions: result[5] != null
          ? PlaytimeExtensions.decode(result[5]! as List<Object?>)
          : null,
    );
  }
}

/// The model that represents the status for SDK
class PlaytimeStatusDetails {
  PlaytimeStatusDetails({
    required this.isFraud,
  });

  /// A flag indicating if the current user is marked as a fraud user.
  bool isFraud;

  Object encode() {
    return <Object?>[
      isFraud,
    ];
  }

  static PlaytimeStatusDetails decode(Object result) {
    result as List<Object?>;
    return PlaytimeStatusDetails(
      isFraud: result[0]! as bool,
    );
  }
}

/// The model that represents the status for SDK
class PlaytimeStatus {
  PlaytimeStatus({
    required this.isInitialized,
    required this.details,
  });

  /// A flag indicating if the SDK is successfully initialized.
  bool isInitialized;

  /// Additional information about the SDK status.
  PlaytimeStatusDetails details;

  Object encode() {
    return <Object?>[
      isInitialized,
      details.encode(),
    ];
  }

  static PlaytimeStatus decode(Object result) {
    result as List<Object?>;
    return PlaytimeStatus(
      isInitialized: result[0]! as bool,
      details: PlaytimeStatusDetails.decode(result[1]! as List<Object?>),
    );
  }
}

/// The parameters related to User acquisition metadata.
class PlaytimeParams {
  PlaytimeParams({
    this.uaNetwork,
    this.uaChannel,
    this.uaSubPublisherCleartext,
    this.uaSubPublisherEncrypted,
    this.placement,
    this.promotionTag,
  });

  /// User acquisition network where the user came from.
  String? uaNetwork;

  /// User acquisition channel where the user came from; e.g. video, offerwall.
  String? uaChannel;

  /// User acquisition sub ID in clear text where the user came from.
  String? uaSubPublisherCleartext;

  /// User acquisition sub ID in encrypted form where the user came from.
  String? uaSubPublisherEncrypted;

  /// The placement of the Playtime experience; e.g. “home screen”, “more options menu”.
  String? placement;

  /// Promotion tag to trigger user-level promotions.
  String? promotionTag;

  Object encode() {
    return <Object?>[
      uaNetwork,
      uaChannel,
      uaSubPublisherCleartext,
      uaSubPublisherEncrypted,
      placement,
      promotionTag,
    ];
  }

  static PlaytimeParams decode(Object result) {
    result as List<Object?>;
    return PlaytimeParams(
      uaNetwork: result[0] as String?,
      uaChannel: result[1] as String?,
      uaSubPublisherCleartext: result[2] as String?,
      uaSubPublisherEncrypted: result[3] as String?,
      placement: result[4] as String?,
      promotionTag: result[5] as String?,
    );
  }
}

/// Additional user information.
class PlaytimeUserProfile {
  PlaytimeUserProfile({
    this.gender,
    this.birthday,
  });

  /// The user's gender. Must be one of 'male', 'female' or 'unknown'.
  String? gender;

  /// ISO8601 timestamp designating user’s birthday, e.g. 2025-06-26T14:45:30.123Z.
  String? birthday;

  Object encode() {
    return <Object?>[
      gender,
      birthday,
    ];
  }

  static PlaytimeUserProfile decode(Object result) {
    result as List<Object?>;
    return PlaytimeUserProfile(
      gender: result[0] as String?,
      birthday: result[1] as String?,
    );
  }
}

/// Rewarded action representation.
/// @basicnodoc
class PlaytimeRewardAction {
  PlaytimeRewardAction({
    this.name,
    this.taskDescription,
    required this.taskType,
    this.playDuration,
    this.level,
    this.amount,
    this.rewardedAt,
    this.rewardsCount,
    this.completedRewards,
    this.timedCoinsDuration,
    this.timedCoins,
    this.originalCoins,
    this.isTimed,
    this.isRewardedForPromotion,
    this.boosterExpiresAt,
  });

  /// Reward action name.
  String? name;

  /// Description of the task.
  String? taskDescription;

  /// Type of task to complete. Possible values: sequential, bonus, playtime.
  String taskType;

  /// Duration (in seconds) of play time required to reward a time-based event. Currently not supported on iOS.
  int? playDuration;

  /// The level number of the time-based event. Currently not supported on iOS.
  int? level;

  /// The amount of coins or rewards the user will receive upon completing the event.
  int? amount;

  /// Timestamp when a reward was granted (ISO 8601).
  String? rewardedAt;

  /// Number of times that the action can be rewarded, applicable to repetitive events.
  int? rewardsCount;

  /// Number of times that the action has been rewarded, applicable to repetitive events.
  int? completedRewards;

  /// Time window (in minutes) during which the Booster reward is applicable.
  int? timedCoinsDuration;

  /// Amount of coins rewarded during the booster period.
  int? timedCoins;

  /// Amount of coins that would be rewarded without any bonuses applied.
  int? originalCoins;

  /// Flag indicating whether the event is a booster event.
  bool? isTimed;

  /// Flag indicating whether the event has been rewarded with promotion.
  bool? isRewardedForPromotion;

  /// The timestamp (ISO 8601) indicating when the booster reward expires.
  /// Use it to determine user eligibility for booster rewards and support features such as booster countdown.
  String? boosterExpiresAt;

  Object encode() {
    return <Object?>[
      name,
      taskDescription,
      taskType,
      playDuration,
      level,
      amount,
      rewardedAt,
      rewardsCount,
      completedRewards,
      timedCoinsDuration,
      timedCoins,
      originalCoins,
      isTimed,
      isRewardedForPromotion,
      boosterExpiresAt,
    ];
  }

  static PlaytimeRewardAction decode(Object result) {
    result as List<Object?>;
    return PlaytimeRewardAction(
      name: result[0] as String?,
      taskDescription: result[1] as String?,
      taskType: result[2]! as String,
      playDuration: result[3] as int?,
      level: result[4] as int?,
      amount: result[5] as int?,
      rewardedAt: result[6] as String?,
      rewardsCount: result[7] as int?,
      completedRewards: result[8] as int?,
      timedCoinsDuration: result[9] as int?,
      timedCoins: result[10] as int?,
      originalCoins: result[11] as int?,
      isTimed: result[12] as bool?,
      isRewardedForPromotion: result[13] as bool?,
      boosterExpiresAt: result[14] as String?,
    );
  }
}

/// Promotion representation.
/// @basicnodoc
class PlaytimePromotion {
  PlaytimePromotion({
    this.name,
    this.promotionDescription,
    this.boostFactor,
    this.startTime,
    this.endTime,
    this.targetingType,
  });

  /// Promotion name.
  String? name;

  /// Description of the promotion.
  String? promotionDescription;

  /// Boost multiplier for the promotion.
  double? boostFactor;

  /// Promotion start timestamp (ISO 8601).
  String? startTime;

  /// Promotion end timestamp (ISO 8601).
  String? endTime;

  /// Targeting type for high quality users.
  String? targetingType;

  Object encode() {
    return <Object?>[
      name,
      promotionDescription,
      boostFactor,
      startTime,
      endTime,
      targetingType,
    ];
  }

  static PlaytimePromotion decode(Object result) {
    result as List<Object?>;
    return PlaytimePromotion(
      name: result[0] as String?,
      promotionDescription: result[1] as String?,
      boostFactor: result[2] as double?,
      startTime: result[3] as String?,
      endTime: result[4] as String?,
      targetingType: result[5] as String?,
    );
  }
}

/// A interface representing a media item.
/// @basicnodoc
class PlaytimeMedia {
  PlaytimeMedia({
    this.portrait,
    this.landscape,
  });

  /// URL to portrait-oriented media.
  String? portrait;

  /// URL to landscape-oriented media.
  String? landscape;

  Object encode() {
    return <Object?>[
      portrait,
      landscape,
    ];
  }

  static PlaytimeMedia decode(Object result) {
    result as List<Object?>;
    return PlaytimeMedia(
      portrait: result[0] as String?,
      landscape: result[1] as String?,
    );
  }
}

/// Configuration for multi-event rewards.
/// The interface provides detailed information about events and rewards.
/// @basicnodoc
class PlaytimeEventConfig {
  PlaytimeEventConfig({
    required this.sequentialActions,
    required this.bonusActions,
    required this.timeBasedActions,
    this.totalCoinsCollected,
    this.totalCoinsPossible,
    this.cashbackReward,
    required this.multipliersActions,
  });

  /// Array of rewarded events that must be completed in the given order.
  /// These will usually be progress events a user can reach in a game or app.
  List<PlaytimeRewardAction?> sequentialActions;

  /// Array of rewarded events that can be completed in any order.
  /// These will be bonus rewards a user should get on top of the other rewards.
  List<PlaytimeRewardAction?> bonusActions;

  /// Array of events that are rewarded based on the time played.
  List<PlaytimeRewardAction?> timeBasedActions;

  /// Total coins collected by the user.
  int? totalCoinsCollected;

  /// Maximum possible coins for this config.
  int? totalCoinsPossible;

  /// Cashback reward configuration for in-app purchases. A missing value means that the feature
  /// is not supported for the campaign or the SDK.
  PlaytimeCashbackConfig? cashbackReward;

  /// Array of events that multiply the rewards.
  List<PlaytimeRewardActionMultiplier?> multipliersActions;

  Object encode() {
    return <Object?>[
      sequentialActions,
      bonusActions,
      timeBasedActions,
      totalCoinsCollected,
      totalCoinsPossible,
      cashbackReward?.encode(),
      multipliersActions,
    ];
  }

  static PlaytimeEventConfig decode(Object result) {
    result as List<Object?>;
    return PlaytimeEventConfig(
      sequentialActions: (result[0] as List<Object?>?)!.cast<PlaytimeRewardAction?>(),
      bonusActions: (result[1] as List<Object?>?)!.cast<PlaytimeRewardAction?>(),
      timeBasedActions: (result[2] as List<Object?>?)!.cast<PlaytimeRewardAction?>(),
      totalCoinsCollected: result[3] as int?,
      totalCoinsPossible: result[4] as int?,
      cashbackReward: result[5] != null
          ? PlaytimeCashbackConfig.decode(result[5]! as List<Object?>)
          : null,
      multipliersActions: (result[6] as List<Object?>?)!.cast<PlaytimeRewardActionMultiplier?>(),
    );
  }
}

/// Configuration for the Playtime Cashback feature.
/// @basicnodoc
class PlaytimeCashbackConfig {
  PlaytimeCashbackConfig({
    this.exchangeRate,
    this.cashbackDescription,
    this.maxLimitPerCampaignUSD,
    this.maxLimitPerCampaignCoins,
    this.completedRewards,
    this.pendingRewards,
  });

  /// Amount of coins that is to be rewarded per 1 USD of IAP.
  double? exchangeRate;

  /// Description of the cashback reward.
  String? cashbackDescription;

  /// Limit of USD available as cashback reward.
  double? maxLimitPerCampaignUSD;

  /// Limit of coins available as cashback reward.
  double? maxLimitPerCampaignCoins;

  /// Info on completed cashback rewards.
  PlaytimeCashbackReward? completedRewards;

  /// Info on pending cashback rewards.
  PlaytimeCashbackReward? pendingRewards;

  Object encode() {
    return <Object?>[
      exchangeRate,
      cashbackDescription,
      maxLimitPerCampaignUSD,
      maxLimitPerCampaignCoins,
      completedRewards?.encode(),
      pendingRewards?.encode(),
    ];
  }

  static PlaytimeCashbackConfig decode(Object result) {
    result as List<Object?>;
    return PlaytimeCashbackConfig(
      exchangeRate: result[0] as double?,
      cashbackDescription: result[1] as String?,
      maxLimitPerCampaignUSD: result[2] as double?,
      maxLimitPerCampaignCoins: result[3] as double?,
      completedRewards: result[4] != null
          ? PlaytimeCashbackReward.decode(result[4]! as List<Object?>)
          : null,
      pendingRewards: result[5] != null
          ? PlaytimeCashbackReward.decode(result[5]! as List<Object?>)
          : null,
    );
  }
}

/// Cashback reward info.
/// @basicnodoc
class PlaytimeCashbackReward {
  PlaytimeCashbackReward({
    this.totalCoins,
    this.events,
  });

  /// Total amount of coins for given rewarded events group.
  int? totalCoins;

  /// Events in the reward group.
  List<PlaytimeCashbackRewardEvent?>? events;

  Object encode() {
    return <Object?>[
      totalCoins,
      events,
    ];
  }

  static PlaytimeCashbackReward decode(Object result) {
    result as List<Object?>;
    return PlaytimeCashbackReward(
      totalCoins: result[0] as int?,
      events: (result[1] as List<Object?>?)?.cast<PlaytimeCashbackRewardEvent?>(),
    );
  }
}

/// Cashback event.
/// @basicnodoc
class PlaytimeCashbackRewardEvent {
  PlaytimeCashbackRewardEvent({
    this.coins,
    this.processAt,
    this.receivedAt,
  });

  /// Amount of coins granted for the event.
  int? coins;

  /// Timestamp (ISO 8601).
  String? processAt;

  /// Timestamp (ISO 8601).
  String? receivedAt;

  Object encode() {
    return <Object?>[
      coins,
      processAt,
      receivedAt,
    ];
  }

  static PlaytimeCashbackRewardEvent decode(Object result) {
    result as List<Object?>;
    return PlaytimeCashbackRewardEvent(
      coins: result[0] as int?,
      processAt: result[1] as String?,
      receivedAt: result[2] as String?,
    );
  }
}

/// The class provides detailed information about events that multiply rewards.
/// @basicnodoc
class PlaytimeRewardActionMultiplier {
  PlaytimeRewardActionMultiplier({
    this.eventName,
    this.eventDescription,
    this.multiplierFactorPercentage,
    this.multiplierLevels,
    this.status,
    this.usedLevels,
  });

  /// Return the event's name
  String? eventName;

  /// Returns the event's description
  String? eventDescription;

  /// Return the multiplication factor of the coin for the multiplier event. value: 0-100
  int? multiplierFactorPercentage;

  /// Returns the maximum number of levels that can be multiplied by the event
  int? multiplierLevels;

  /// Return the status of the multiplied event:
  /// "Pending": multiplier events not used yet
  /// "Active": multiplier event is currently active
  /// "Finished": multiplier event has been used and finished
  String? status;

  /// Returns the number of levels that has been multiplied by the event
  int? usedLevels;

  Object encode() {
    return <Object?>[
      eventName,
      eventDescription,
      multiplierFactorPercentage,
      multiplierLevels,
      status,
      usedLevels,
    ];
  }

  static PlaytimeRewardActionMultiplier decode(Object result) {
    result as List<Object?>;
    return PlaytimeRewardActionMultiplier(
      eventName: result[0] as String?,
      eventDescription: result[1] as String?,
      multiplierFactorPercentage: result[2] as int?,
      multiplierLevels: result[3] as int?,
      status: result[4] as String?,
      usedLevels: result[5] as int?,
    );
  }
}

/// The model that represents a campaign and/or installed application.
/// @basicnodoc
class PlaytimeCampaign {
  PlaytimeCampaign({
    this.campaignUUID,
    required this.appName,
    required this.appDescription,
    required this.appID,
    this.appBundleID,
    this.appStoreID,
    this.installedAt,
    this.uninstalledAt,
    this.rewardingExpiresAfter,
    this.rewardingExpiresAt,
    this.campaignExpiresAt,
    this.appCategory,
    this.campaignType,
    this.featuredPosition,
    this.score,
    this.iconImage,
    this.image,
    this.video,
    this.promotion,
    this.eventConfig,
    this.isCompleted,
  });

  /// Campaign UUID
  String? campaignUUID;

  /// App name.
  String appName;

  /// Short description of the app.
  String appDescription;

  /// Unique identifier for the app.
  /// On Android, it’s represented by a string in the format com.example.myapp.
  /// On iOS, it’s App Store ID.
  String appID;

  /// On iOS, it’s the ID in the format com.example.myapp.
  String? appBundleID;

  /// On iOS, it’s application's store ID number that is part of the App Store link.
  String? appStoreID;

  /// App installation timestamp (ISO 8601).
  String? installedAt;

  /// App uninstallation timestamp (ISO 8601).
  String? uninstalledAt;

  /// Time (in days) after which rewards expire after installation.
  int? rewardingExpiresAfter;

  /// Expiration timestamp (ISO 8601) denoting how long players can get
  /// rewards after installing the app.
  String? rewardingExpiresAt;

  /// Timestamp (ISO 8601) denoting the maximum amount of time after
  /// fetching the campaign that it can be installed.
  String? campaignExpiresAt;

  /// App category.
  String? appCategory;

  /// Campaign type.
  String? campaignType;

  /// The ordered position for specific featured campaigns.
  int? featuredPosition;

  /// The eCPM of the campaign.
  double? score;

  /// URL to the campaign icon image.
  String? iconImage;

  /// Campaign media assets (portrait & landscape).
  PlaytimeMedia? image;

  /// Campaign video media assets.
  PlaytimeMedia? video;

  /// Active promotion details, if any.
  PlaytimePromotion? promotion;

  /// Event and rewards configuration.
  PlaytimeEventConfig? eventConfig;

  /// Flag indicating whether all rewards have been collected.
  bool? isCompleted;

  Object encode() {
    return <Object?>[
      campaignUUID,
      appName,
      appDescription,
      appID,
      appBundleID,
      appStoreID,
      installedAt,
      uninstalledAt,
      rewardingExpiresAfter,
      rewardingExpiresAt,
      campaignExpiresAt,
      appCategory,
      campaignType,
      featuredPosition,
      score,
      iconImage,
      image?.encode(),
      video?.encode(),
      promotion?.encode(),
      eventConfig?.encode(),
      isCompleted,
    ];
  }

  static PlaytimeCampaign decode(Object result) {
    result as List<Object?>;
    return PlaytimeCampaign(
      campaignUUID: result[0] as String?,
      appName: result[1]! as String,
      appDescription: result[2]! as String,
      appID: result[3]! as String,
      appBundleID: result[4] as String?,
      appStoreID: result[5] as String?,
      installedAt: result[6] as String?,
      uninstalledAt: result[7] as String?,
      rewardingExpiresAfter: result[8] as int?,
      rewardingExpiresAt: result[9] as String?,
      campaignExpiresAt: result[10] as String?,
      appCategory: result[11] as String?,
      campaignType: result[12] as String?,
      featuredPosition: result[13] as int?,
      score: result[14] as double?,
      iconImage: result[15] as String?,
      image: result[16] != null
          ? PlaytimeMedia.decode(result[16]! as List<Object?>)
          : null,
      video: result[17] != null
          ? PlaytimeMedia.decode(result[17]! as List<Object?>)
          : null,
      promotion: result[18] != null
          ? PlaytimePromotion.decode(result[18]! as List<Object?>)
          : null,
      eventConfig: result[19] != null
          ? PlaytimeEventConfig.decode(result[19]! as List<Object?>)
          : null,
      isCompleted: result[20] as bool?,
    );
  }
}

/// The response of the SDK containing campaigns.
/// @basicnodoc
class PlaytimeCampaignsResponse {
  PlaytimeCampaignsResponse({
    required this.campaigns,
  });

  /// The requested selection of campaigns.
  List<PlaytimeCampaign?> campaigns;

  Object encode() {
    return <Object?>[
      campaigns,
    ];
  }

  static PlaytimeCampaignsResponse decode(Object result) {
    result as List<Object?>;
    return PlaytimeCampaignsResponse(
      campaigns: (result[0] as List<Object?>?)!.cast<PlaytimeCampaign?>(),
    );
  }
}

/// Permissions granted by the user.
/// @basicnodoc
class PlaytimePermissions {
  PlaytimePermissions({
    required this.isTOSAccepted,
    required this.isUsagePermissionAccepted,
  });

  /// Flag indicating whether the terms of service are accepted.
  bool isTOSAccepted;

  /// Flag indicating whether the usage permission is accepted.
  bool isUsagePermissionAccepted;

  Object encode() {
    return <Object?>[
      isTOSAccepted,
      isUsagePermissionAccepted,
    ];
  }

  static PlaytimePermissions decode(Object result) {
    result as List<Object?>;
    return PlaytimePermissions(
      isTOSAccepted: result[0]! as bool,
      isUsagePermissionAccepted: result[1]! as bool,
    );
  }
}

/// SDK response containing permissions.
/// @basicnodoc
class PlaytimePermissionsResponse {
  PlaytimePermissionsResponse({
    required this.permissions,
  });

  /// Permissions granted by the user.
  PlaytimePermissions permissions;

  Object encode() {
    return <Object?>[
      permissions.encode(),
    ];
  }

  static PlaytimePermissionsResponse decode(Object result) {
    result as List<Object?>;
    return PlaytimePermissionsResponse(
      permissions: PlaytimePermissions.decode(result[0]! as List<Object?>),
    );
  }
}

class _PlaytimeCodec extends StandardMessageCodec {
  const _PlaytimeCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PlaytimeExtensions) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeOptions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeParams) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeParams) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeStatus) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeStatusDetails) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeUserProfile) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PlaytimeExtensions.decode(readValue(buffer)!);
      case 129: 
        return PlaytimeOptions.decode(readValue(buffer)!);
      case 130: 
        return PlaytimeOptions.decode(readValue(buffer)!);
      case 131: 
        return PlaytimeParams.decode(readValue(buffer)!);
      case 132: 
        return PlaytimeParams.decode(readValue(buffer)!);
      case 133: 
        return PlaytimeStatus.decode(readValue(buffer)!);
      case 134: 
        return PlaytimeStatusDetails.decode(readValue(buffer)!);
      case 135: 
        return PlaytimeUserProfile.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The entry point of adjoe Playtime SDK.
class Playtime {
  /// Constructor for [Playtime].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  Playtime({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PlaytimeCodec();

  /// Initializes the Playtime SDK.
  /// You must initialize the Playtime SDK before you can use any of its features.
  /// The initialization will run asynchronously in the background
  /// Supported only on Android
  Future<void> init(String apiKey, PlaytimeOptions? options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.init';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[apiKey, options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Opens a new activity that shows catalog.
  /// Supported only on Android.
  Future<void> showCatalog(PlaytimeParams? params) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.showCatalog';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[params]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Opens a new activity that shows catalog.
  /// Supported on both Android and iOS.
  Future<void> showCatalogWithOptions(PlaytimeOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.showCatalogWithOptions';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Sets the Playtime options.
  /// Supported on both Android and iOS.
  Future<void> setPlaytimeOptions(PlaytimeOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.setPlaytimeOptions';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Sets the User-Acquisition (UA) parameters.
  /// Supported only on Android.
  Future<void> setUAParams(PlaytimeParams params) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.setUAParams';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[params]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns the version code of the Playtime SDK.
  /// Supported only on Android.
  Future<String> getVersion() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.getVersion';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  /// Returns the version name of the Playtime SDK.
  /// Supported only on Android.
  Future<String> getVersionName() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.getVersionName';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  /// Checks whether the Playtime SDK is initialized.
  /// Supported only on Android.
  Future<bool> isInitialized() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.isInitialized';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  /// Checks whether the user has accepted the Playtime Terms of Service (TOS).
  /// Supported only on Android.
  Future<bool> hasAcceptedTOS() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.hasAcceptedTOS';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  /// Checks whether the user has given access to the usage statistics.
  /// Supported only on Android.
  Future<bool> hasAcceptedUsagePermission() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.hasAcceptedUsagePermission';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  /// Returns the unique ID of the user by which he is identified within the Playtime services.
  /// Supported only on Android.
  Future<String?> getUserId() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.getUserId';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return (__pigeon_replyList[0] as String?);
    }
  }

  /// Sends a user event to Playtime.
  /// These events help to improve the accuracy of the app recommendations for the user.
  /// Supported only on Android.
  Future<void> sendEvent(int event, String extra, PlaytimeParams? params) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.sendEvent';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[event, extra, params]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Recieve the status of SDK.
  /// Supported on Android and iOS.
  Future<PlaytimeStatus> getStatus() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.Playtime.getStatus';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PlaytimeStatus?)!;
    }
  }
}

class _PlaytimeStudioCodec extends StandardMessageCodec {
  const _PlaytimeStudioCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PlaytimeCampaign) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeCampaign) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeCampaignsResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeCashbackConfig) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeCashbackReward) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeCashbackRewardEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeEventConfig) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeExtensions) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeMedia) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeOptions) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeParams) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimePermissions) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimePermissionsResponse) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimePromotion) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeRewardAction) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeRewardActionMultiplier) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is PlaytimeUserProfile) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PlaytimeCampaign.decode(readValue(buffer)!);
      case 129: 
        return PlaytimeCampaign.decode(readValue(buffer)!);
      case 130: 
        return PlaytimeCampaignsResponse.decode(readValue(buffer)!);
      case 131: 
        return PlaytimeCashbackConfig.decode(readValue(buffer)!);
      case 132: 
        return PlaytimeCashbackReward.decode(readValue(buffer)!);
      case 133: 
        return PlaytimeCashbackRewardEvent.decode(readValue(buffer)!);
      case 134: 
        return PlaytimeEventConfig.decode(readValue(buffer)!);
      case 135: 
        return PlaytimeExtensions.decode(readValue(buffer)!);
      case 136: 
        return PlaytimeMedia.decode(readValue(buffer)!);
      case 137: 
        return PlaytimeOptions.decode(readValue(buffer)!);
      case 138: 
        return PlaytimeParams.decode(readValue(buffer)!);
      case 139: 
        return PlaytimePermissions.decode(readValue(buffer)!);
      case 140: 
        return PlaytimePermissionsResponse.decode(readValue(buffer)!);
      case 141: 
        return PlaytimePromotion.decode(readValue(buffer)!);
      case 142: 
        return PlaytimeRewardAction.decode(readValue(buffer)!);
      case 143: 
        return PlaytimeRewardActionMultiplier.decode(readValue(buffer)!);
      case 144: 
        return PlaytimeUserProfile.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The entry point of Adjoe Playtime SDK in Studio version. This namespace provides
/// methods to fetch campaigns and installed apps to show them in your custom UI.
/// @basicnodoc
class PlaytimeStudio {
  /// Constructor for [PlaytimeStudio].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PlaytimeStudio({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PlaytimeStudioCodec();

  /// Get the list of offers that a user can install.
  /// Supported on both Android and iOS.
  Future<PlaytimeCampaignsResponse> getCampaigns(PlaytimeOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.getCampaigns';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PlaytimeCampaignsResponse?)!;
    }
  }

  /// Get the list of apps the user has already installed and that will contain the progress the user has made already.
  /// Supported on both Android and iOS.
  Future<PlaytimeCampaignsResponse> getInstalledCampaigns(PlaytimeOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.getInstalledCampaigns';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PlaytimeCampaignsResponse?)!;
    }
  }

  /// Use this method to forward the user to the store.
  /// Supported on both Android and iOS.
  Future<void> openInStore(PlaytimeCampaign campaign) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.openInStore';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[campaign]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Use this method to forward the user to the app.
  /// Supported on both Android and iOS.
  Future<void> openInstalledCampaign(PlaytimeCampaign campaign) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.openInstalledCampaign';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[campaign]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get user’s permissions.
  /// Supported only on Android.
  Future<PlaytimePermissionsResponse> getPermissions() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.getPermissions';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PlaytimePermissionsResponse?)!;
    }
  }

  /// Show the prompt requesting user’s permissions.
  /// Supported only on Android.
  Future<PlaytimePermissionsResponse> showPermissionsPrompt() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.showPermissionsPrompt';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PlaytimePermissionsResponse?)!;
    }
  }

  /// Opens the register popup for rewards connect.
  /// Supported for both android and iOS.
  Future<void> registerRewardsConnect() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.registerRewardsConnect';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Resets the rewards connect registration.
  /// Supported for both android and iOS.
  Future<void> resetRewardsConnect() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.resetRewardsConnect';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Use this method to deeplink installed apps
  /// Supported for both android and iOS.
  Future<void> _showInstalledApps() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.showInstalledApps';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Use this method to deeplink app details
  /// Supported for both android and iOS.
  Future<void> _showAppDetails(PlaytimeCampaign campaign) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.showAppDetails';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[campaign]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Use this method to deeplink app details with token
  /// Supported for both android and iOS.
  Future<void> _showAppDetailsWithToken(String token, String campaignAppId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.showAppDetailsWithToken';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[token, campaignAppId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Use this method to forward the open chatbot
  /// Supported for both android and iOS.
  Future<void> _openChatbot(PlaytimeCampaign? campaign) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.adjoe.PlaytimeStudio.openChatbot';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[campaign]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}
